CREATE TABLE `order_summary` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INTERVAL_TIMESTAMP` varchar(45) DEFAULT NULL,
  `PRODUCT` varchar(45) DEFAULT NULL,
  `TOTAL_VALUE` double DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
